name: Test Adapter

on:
  push:
    branches:
      - main
      - "dev/**"
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test (Node ${{ matrix.node }} · ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-npm-

      - name: Install
        run: npm ci

      - name: Validate JSON
        run: |
          npx jsonlint -q package.json
          npx jsonlint -q io-package.json

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm test
