name: i18n Auto-Translate

on:
  push:
    branches: [ main, master ]
    paths:
      - 'admin/**'
      - 'io-package.json'
      - 'package.json'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run translator
        run: npm run translate

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet; then
            git config user.name  "iobroker-translate-bot"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "chore(i18n): auto-translate updated strings [skip ci]"
            git push
          else
            echo "No translation changes."
          fi
